"use client"
import React, { useEffect, useState } from "react";
import Head from "next/head";
import Navbar from "./components/Navbar";
import Main from "./components/Main";
import About from "./components/About";
import Skills from "./components/Skills";
import Projetcs from "./components/Projetcs";
import Contact from "./components/Contact";

import WaterDropGrid from "./components/WaterDropGridVideo";
import { Parallax, ParallaxLayer } from "@react-spring/parallax";

const Page = () => {
  const [offset, setOffset] = useState(0);

  useEffect(() => {
    const handleResize = () => {
      const screenWidth = window.innerWidth;

      if (screenWidth >= 1200) {
        setOffset(0);
      } else if (screenWidth >= 992) {
        setOffset(1);
      } else if (screenWidth >= 768) {
        setOffset(2);
      } else {
        setOffset(3);
      }
    };

    // Initial offset calculation
    handleResize();

    window.addEventListener("resize", handleResize);

    return () => {
      window.removeEventListener("resize", handleResize);
    };
  }, []);

  useEffect(() => {
    // Apply smooth scrolling to the Parallax component's container
    const parallaxContainer = document.querySelector(".parallax-container");
    if (parallaxContainer) {
      parallaxContainer.style.scrollBehavior = "smooth";
    }

    // Clean up on component unmount
    return () => {
      if (parallaxContainer) {
        parallaxContainer.style.scrollBehavior = ""; // Reset scroll behavior
      }
      document.body.style.fontFamily = ""; // Reset font family
    };
  }, []);

  return (
    <div>
      <Head>
        <title>Clint | Front-End Developer</title>
        <meta name="description" content="Generated by create next app"></meta>
        <link rel="icon" href="/favicon.ico"></link>
      </Head>
      <Navbar />
      <Parallax pages={6.5} className="parallax-container ">
        <ParallaxLayer speed={1} >
          <Main />
        </ParallaxLayer>

        <ParallaxLayer offset={offset + 0}>\
          <WaterDropGrid/>
        </ParallaxLayer>

        <ParallaxLayer offset={offset + 1}>
          <About />
        </ParallaxLayer>

        <ParallaxLayer offset={offset + 2}>
          <Skills />
        </ParallaxLayer>

        <ParallaxLayer offset={offset + 3}>
          <Projetcs />
        </ParallaxLayer>

        <ParallaxLayer offset={offset + 5}>
          <Contact />
        </ParallaxLayer>
      </Parallax>
    </div>
  );
};

export default Page;